version: 1.0.{build}

cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore

after_build:
  - ps: chcp 65001
  - ps: .\test\bin\Debug\test.exe --summary

test: off