version: 1.0.{build}

cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore

before_test:
  - ps: chcp 65001

test: off

after_test:
  - ps: ./test/bin/Release/test.exe --summary