version: 1.0.{build}

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer

cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore

after_build:
  - ps: chcp 65001
  - ps: .\test\bin\Debug\test.exe --summary-location | ruby appveyor.rb

test: off